name: Auto Comment on Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment to Issue
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const commentBody = `### Thank you for raising this issue!\nWe'll review it as soon as possible. We truly appreciate your contributions! ✨\n\n> Meanwhile make sure you've visited the README.md, CONTRIBUTING.md, and CODE_OF_CONDUCT.md before creating a PR for this. Also, please do NOT create a PR until this issue has been assigned to you. 😊`;

            const { data: comments } = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: number,
            });

            const hasComment = comments.some(comment => comment.body.includes('Thank you for raising this issue!'));

            if (!hasComment) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: number,
                body: commentBody,
              });
              console.log('Comment added successfully.');
            } else {
              console.log('A similar comment already exists. No new comment was added.');
            }